# ServerHealth Environment Variable Test Configuration
# This file shows how to use environment variables with the modular system

# Monitoring Configuration
disk:
  enabled: true
  threshold: 80
  check_interval: 12  # hours
  max_daily_alerts: 5

cpu:
  enabled: true
  threshold: 85
  check_interval: 60  # minutes
  max_daily_alerts: 5

memory:
  enabled: true
  threshold: 85
  check_interval: 60  # minutes
  max_daily_alerts: 5

# Notification Providers (can be overridden by environment variables)
notifications:
  - type: slack
    enabled: true
    webhook_url: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"

  - type: telegram
    enabled: true
    bot_token: "1234567890:ABCdefGHIjklMNOpqrsTUVwxyz"
    chat_id: "123456789"

  - type: discord
    enabled: true
    webhook_url: "https://discord.com/api/webhooks/123456789012345678/abcdefghijklmnopqrstuvwxyz1234567890123456789012345678901234567890"

# General Settings
log_level: info
service_name: serverhealth

# Environment Variables to override this configuration:
# export SERVERHEALTH_DISK_THRESHOLD=90
# export SERVERHEALTH_CPU_THRESHOLD=95
# export SERVERHEALTH_MEMORY_THRESHOLD=90
# export SERVERHEALTH_LOG_LEVEL=debug
# export SERVERHEALTH_NOTIFICATIONS_0_WEBHOOK_URL="https://hooks.slack.com/services/YOUR/ACTUAL/WEBHOOK"
# export SERVERHEALTH_NOTIFICATIONS_1_BOT_TOKEN="YOUR_ACTUAL_BOT_TOKEN"
# export SERVERHEALTH_NOTIFICATIONS_1_CHAT_ID="YOUR_ACTUAL_CHAT_ID"
# export SERVERHEALTH_NOTIFICATIONS_2_WEBHOOK_URL="https://discord.com/api/webhooks/YOUR/ACTUAL/WEBHOOK"
